

spring:
  datasource:
    url: jdbc:mysql://192.168.169.188:3307/gmall_pms?useUnicode=true&useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
    host: 192.168.169.188
    database: 0
    port: 6379


dubbo:
  application:
    name: gmall-pms
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://192.168.169.188:2182
  consumer:
    check: false



mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
