spring:
  datasource:
    url: jdbc:mysql://192.168.169.188:3307/gmall_ums?useUnicode=true&useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root



dubbo:
  application:
    name: gmall-ums
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://192.168.169.188:2182
  consumer:
    check: false

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
